# Generated by Django 4.2.6 on 2023-10-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_indi',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('metaIndi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InfoMed',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('concentracion', models.CharField(max_length=300)),
                ('presentacion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda_realidades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.infomed')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoAnterior', models.IntegerField()),
                ('fecha', models.DateField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.infomed')),
            ],
        ),
        migrations.CreateModel(
            name='indi_mensuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaMes', models.IntegerField()),
                ('fecha', models.DateField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.admin_indi')),
            ],
        ),
        migrations.CreateModel(
            name='DemandaReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda_real', models.IntegerField()),
                ('fecha', models.DateField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.infomed')),
            ],
        ),
        migrations.CreateModel(
            name='demanda_diarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado', models.IntegerField()),
                ('no_entregado', models.IntegerField()),
                ('fecha', models.DateField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.infomed')),
            ],
            options={
                'db_table': 'demanda_diaria_db',
            },
        ),
        migrations.CreateModel(
            name='AdminMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.infomed')),
            ],
        ),
    ]
